/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestNative */

#ifndef _Included_TestNative
#define _Included_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestNative
 * Method:    methodDemo
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TestNative_methodDemo
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
